travis:
  secure:
    BINSTAR_TOKEN: RRmpFl37vZcFPrsi1P1R4s2IFaCYTIR1TyALzpNiPdFpa9itz4RBIh3xjb+PR3Cb/JRGi5OP46Z4a3+USHDvHVMXOupNtodXsRSDl11UKoXs1trOQMYGeXRJ/SuTWSlignqcu82MVSFh0VFAzFyvjfXMZYboJCFtpgWOWyPwOoTEabafnIz2YkpXvFZTNo5ZXtOr6OJDDSDZ3ClDG5VanMSyWF3KV6JdVlhOsPPXGcej9oUxZ80tuv27+zhwgctUVrr46okXeSbvkvj//NvD+R1zhOO7jIDmFL8j03oxkqnaXE5DPfmMjeiS7c3+NlZglUfMh8mb/PFpZ3APxRw5/WaUIU0yhcSS1ytjUvhNcxlxqnYVo5dLQHVYFsUDtK2HMChq85Lgr/FI4tcZ16BO8PALFBytiXfMseIRIKybBFdHrkFCTnU6p6BC71O0zIHU43HGinjhOgKQzK5iUwg4qG+mMKTK/Qun1Sb+RWY1g4dIgRa+iTZIsNZkcVB0wp+HGn009HT7HRg6ELZpj+Al/uwA8WEM2p2W5rgCrov3lG1lfkh0sl69BWEJEx6YJ1nk6BUJKSWa+1y++eK+ydaoOCOGZ/Au+9kQlnu/ABKeW1plyRjAXl4YwrtIaebdlcVkWMZS2XLtqyLBAPjuRowefPgbuhAUVYUTrD+iZTB3/Vo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
