travis:
  secure:
    BINSTAR_TOKEN: mG8rmXeq1BdDVkS/IahAEwxzKmK2KIWMxY9pE4Py8feVNX243kUpVK5R4o55yXzj8aoTyYNdDEWXDa6mCuBh3BT9UuGUg+ixMxtFh3gfApZr1ftTgiroWZQH0iWyWghbVX4aRO+VXvnY0BvaAFDThOCEV/Dzf9c9CHYhZhPBXSFVXPKTMZSAot8U+enkkN4IZ34Rn502Fhow7dmOEoIHkiia0/IIhrGYEhEjnMBdVGC9GbQ9R1C4hp/SO8VMcUHiqsq4ImICrzAQqRfoCox7KQPCMcyQg70k7Zf6Z7QV1uDgPr00bDPbuQzrkKuU7nlEyZujcDvYZ9+xYMTYA9TMA9nIsX1NZCJKZGD1e6YBRMfdOSwnMg3LF4t2R68VuBPLxBW4yNaIYdVYUgjL+ollf/+f+KrvKGRPfg1BphEEeZYD5D72HlD7Bb4WrOo4727lzjpilU9SPEDhtXT56fSdf7Xi3HO8R4JK7Pm1voASXEf2bdKQ00IHy0QoXe3K+mT3t0PdZPVrsG0Et+kAOES1JnBJOw1xuTzbGOlAA+j3dlz4n+WAUInmbRY5EeIdUqLgvk1i0CGUzyoGgLKNVTGbmn8PqZAr5ejgy1TEInII1nEQr9IVEaMup3EPm/zSBJ10M5H6EnVr551OUyiS8ZYAXr31OygmKvCm3D1M88lGqYw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
